export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_COUNTRY = 'FETCH_COUNTRY';
export const SET_TERM = 'SET_TERM';
export const SELECT_REGION = 'SELECT_REGION';
export const SET_RENDERED = 'SET_RENDERED';
export const RESET_RENDERED = 'RESET_RENDERED';
